integrate: integrate Namespace Reference
integrate Namespace Reference
Functions
template<typename Real , typename State >
const void stepEuler (Real &time, State &state, const Real stepSize, const std::function< const State(const Real time, const State &state)> &computeStateDerivative)
Execute single integration step using Euler scheme.
template<typename Real , typename State >
const void stepRK4 (Real &time, State &state, const Real stepSize, const std::function< const State(const Real time, const State &state) > &computeStateDerivative)
Execute single integration step using Runge-Kutta 4 scheme.
template<typename Real , typename State >
const void stepRKF45 (Real &time, State &state, Real &stepSize, const std::function< const State(const Real time, const State &state)> &computeStateDerivative, const Real tolerance, const Real minimumStepSize, const Real maximumStepSize)
Execute single integration step using Runge-Kutta-Felhberg 4(5) scheme.
template<typename Real , typename State >
const void stepRKF78 (Real &time, State &state, Real &stepSize, const std::function< const State(const Real time, const State &state)> &computeStateDerivative, const Real tolerance, const Real minimumStepSize, const Real maximumStepSize)
Execute single integration step using Runge-Kutta-Felhberg 7(8) scheme.
Function Documentation
stepEuler()
template<typename Real , typename State > const void integrate::stepEuler (Real & time, State & state, const Real stepSize, const std::function< const State(const Real time, const State &state)> & computeStateDerivative)
Executes single numerical integration step using Euler scheme.
Template Parameters
Real Type for floating-point number
State Type for state and state derivative
Parameters
[in,out] time Independent variable, which is provided as input and is updated with output at end of integration step
[in,out] state State, which is provided as input and is updated with output at end of integration step
[in] stepSize Step size to take for integration step
[in] computeStateDerivative Function to compute state derivative for current time and state
Definition at line 29 of file euler.hpp.
stepRK4()
template<typename Real , typename State > const void integrate::stepRK4 (Real & time, State & state, const Real stepSize, const std::function< const State(const Real time, const State &state) > & computeStateDerivative)
Executes single numerical integration step using Runge-Kutta 4 scheme.
Template Parameters
Real Type for floating-point number
State Type for state and state derivative
Parameters
[in,out] time Independent variable, which is provided as input and is updated with output at end of integration step
[in,out] state State, which is provided as input and is updated with output at end of integration step
[in] stepSize Step size to take for integration step
[in] computeStateDerivative Function to compute state derivative for current time and state
Definition at line 29 of file rk4.hpp.
stepRKF45()
template<typename Real , typename State > const void integrate::stepRKF45 (Real & time, State & state, Real & stepSize, const std::function< const State(const Real time, const State &state)> & computeStateDerivative, const Real tolerance, const Real minimumStepSize, const Real maximumStepSize)
Executes single numerical integration step using Runge-Kutta-Felhberg 4(5) scheme.
Template Parameters
Real Type for floating-point number
State Type for state and state derivative
Parameters
[in,out] time Independent variable, which is provided as input and is updated with output at end of integration step
[in,out] state State, which is provided as input and is updated with output at end of integration step
[in,out] stepSize Step size to take for integration step
[in] computeStateDerivative Function to compute state derivative for current time and state
[in] tolerance Local truncation error tolerance
[in] minimumStepSize Minimum allowable step size for integration step
[in] maximumStepSize Maximum allowable step size for integration step
Definition at line 35 of file rkf45.hpp.
References stepRKF45().
Referenced by stepRKF45(), and stepRKF78().
stepRKF78()
template<typename Real , typename State > const void integrate::stepRKF78 (Real & time, State & state, Real & stepSize, const std::function< const State(const Real time, const State &state)> & computeStateDerivative, const Real tolerance, const Real minimumStepSize, const Real maximumStepSize)
Executes single numerical integration step using Runge-Kutta-Felhberg 7(8) scheme.
Template Parameters
Real Type for floating-point number
State Type for state and state derivative
Parameters
[in,out] time Independent variable, which is provided as input and is updated with output at end of integration step
[in,out] state State, which is provided as input and is updated with output at end of integration step
[in,out] stepSize Step size to take for integration step
[in] computeStateDerivative Function to compute state derivative for current time and state
[in] tolerance Local truncation error tolerance
[in] minimumStepSize Minimum allowable step size for integration step
[in] maximumStepSize Maximum allowable step size for integration step
Definition at line 35 of file rkf78.hpp.
References stepRKF45().